export var E_CONDITION_EFFECTS;
(function (E_CONDITION_EFFECTS) {
    E_CONDITION_EFFECTS["DISPLAY"] = "display";
    E_CONDITION_EFFECTS["ENABLE"] = "enable";
})(E_CONDITION_EFFECTS || (E_CONDITION_EFFECTS = {}));
export var E_FIELD_CONDITION_TYPES;
(function (E_FIELD_CONDITION_TYPES) {
    E_FIELD_CONDITION_TYPES["RANGE"] = "range";
    E_FIELD_CONDITION_TYPES["PATTERN"] = "pattern";
    E_FIELD_CONDITION_TYPES["VALUE"] = "value";
    E_FIELD_CONDITION_TYPES["VALUES"] = "values";
})(E_FIELD_CONDITION_TYPES || (E_FIELD_CONDITION_TYPES = {}));
